import 'package:flutter/material.dart';
import 'package:quran_app/features/quran/tajweed/tajweed_rule_model.dart';

class TajweedData {
  static const List<TajweedRuleModel> rules = [
    TajweedRuleModel(
      id: '1',
      title: 'المد الطبيعي',
      shortDescription: 'مقدار مده حركتان',
      detailedExplanation: 'هو الذي لا تقوم ذات الحرف إلا به ولا يتوقف على سبب من همز أو سكون. يمد مقدار حركتين.',
      exampleWord: 'نُوحِيهَا',
      color: Colors.orange,
      category: 'أحكام المد',
    ),
    TajweedRuleModel(
      id: '2',
      title: 'المد المتصل',
      shortDescription: 'مده 4 أو 5 حركات وجوباً',
      detailedExplanation: 'أن يقع الهمز بعد حرف المد في كلمة واحدة. يجب مده 4 أو 5 حركات.',
      exampleWord: 'السَّمَاءَ',
      color: Color(0xFFF06292), // Pink
      category: 'أحكام المد',
    ),
    TajweedRuleModel(
      id: '3',
      title: 'المد المنفصل',
      shortDescription: 'مده 4 أو 5 حركات جوازاً',
      detailedExplanation: 'أن يقع حرف المد في آخر الكلمة الأولى والهمز في أول الكلمة الثانية. يجوز مده وقصره.',
      exampleWord: 'بِمَا أُنزِلَ',
      color: Color(0xFFF06292), // Pink
      category: 'أحكام المد',
    ),
    TajweedRuleModel(
      id: '4',
      title: 'المد اللازم',
      shortDescription: 'مده 6 حركات لزوماً',
      detailedExplanation: 'أن يقع السكون الأصلي بعد حرف المد أو اللين في كلمة أو حرف. يلزمه المد 6 حركات لكل القرّاء.',
      exampleWord: 'الضَّآلِّينَ',
      color: Colors.red,
      category: 'أحكام المد',
    ),
    TajweedRuleModel(
      id: '5',
      title: 'الغنة',
      shortDescription: 'صوت يخرج من الخيشوم، حركتان',
      detailedExplanation: 'الغنة هي صوت أغن يخرج من الخيشوم. وتكون أكمل ما تكون في النون والميم المشددتين.',
      exampleWord: 'إِنَّ / مِمَّا',
      color: Colors.green,
      category: 'أحكام النون والميم',
    ),
    TajweedRuleModel(
      id: '6',
      title: 'الإخفاء الحقيقي',
      shortDescription: 'إخفاء النون الساكنة مع بقاء الغنة',
      detailedExplanation: 'النطق بالحرف بصفة بين الإظهار والإدغام عارياً عن التشديد مع بقاء الغنة. حروفه (15) حرفاً مجموعة في أوائل كلم: صف ذا ثنا كم جاد شخص قد سما دم طيبا زد في تقى ضع ظالما.',
      exampleWord: 'مِن قَبْلُ',
      color: Colors.green,
      category: 'أحكام النون الساكنة والتنوين',
    ),
    TajweedRuleModel(
      id: '7',
      title: 'الإظهار الحلقي',
      shortDescription: 'بيان الحرف نطقاً بلا غنة ظاهرة',
      detailedExplanation: 'إخراج كل حرف من مخرجه من غير غنة في الحرف المظهر. حروفه مجموعة في أوائل: أخي هاك علما حازه غير خاسر.',
      exampleWord: 'مِنْ خَوْفٍ',
      color: Colors.teal,
      category: 'أحكام النون الساكنة والتنوين',
    ),
    TajweedRuleModel(
      id: '8',
      title: 'الإدغام بغنة',
      shortDescription: 'إدخال النون في (ينمو) مع الغنة',
      detailedExplanation: 'إدخال حرف ساكن في متحرك بحيث يصيران حرفاً واحداً مشدداً. يقع الإدغام بغنة في (ي، ن، م، و).',
      exampleWord: 'مِن وَالٍ',
      color: Colors.purple,
      category: 'أحكام النون الساكنة والتنوين',
    ),
    TajweedRuleModel(
      id: '9',
      title: 'الإدغام بغير غنة',
      shortDescription: 'إدخال النون في (ل، ر) بلا غنة',
      detailedExplanation: 'إدغام النون الساكنة والتنوين في حرفي اللام والراء من غير غنة (إدغام كامل).',
      exampleWord: 'مِن رَّبِّهِمْ',
      color: Colors.grey,
      category: 'أحكام النون الساكنة والتنوين',
    ),
    TajweedRuleModel(
      id: '10',
      title: 'الإقلاب',
      shortDescription: 'قلب النون ميما عند الباء',
      detailedExplanation: 'قلب النون الساكنة أو التنوين ميماً مخفاة بغنة عند ملاقاة حرف الباء.',
      exampleWord: 'مِنۢ بَعْدِ',
      color: Colors.brown,
      category: 'أحكام النون الساكنة والتنوين',
    ),
    TajweedRuleModel(
      id: '11',
      title: 'القلقلة',
      shortDescription: 'اضطراب الصوت عند النطق بالحرف',
      detailedExplanation: 'اهتزاز المخرج بالحرف الساكن حتى يسمع له نبرة قوية. حروفها خمسة: (قطب جد).',
      exampleWord: 'يَقْطَعُونَ',
      color: Colors.blue,
      category: 'صفات الحروف',
    ),
    TajweedRuleModel(
      id: '12',
      title: 'أحكام الميم الساكنة',
      shortDescription: 'إخفاء، إدغام، أو إظهار الميم',
      detailedExplanation: 'لها ثلاثة أحكام: الإخفاء الشفوي (عند الباء)، الإدغام الشفوي (عند الميم)، والإظهار الشفوي (عند باقي الحروف).',
      exampleWord: 'هُم بِهِ / وَهُم مَّعَهُ / هُمْ يُوقِنُونَ',
      color: Colors.green, // General Ghunnah color
      category: 'أحكام النون والميم',
    ),
    TajweedRuleModel(
      id: '13',
      title: 'التفخيم والترقيق',
      shortDescription: 'تغليظ أو ترقيق صوت الحرف',
      detailedExplanation: 'التفخيم تسمين الحرف (حروفه: خص ضغط قظ). والترقيق تنحيفه (باقي الحروف، ما عدا ل، ر، ا التي تدور بين التفخيم والترقيق).',
      exampleWord: 'خَالِدِينَ / اللَّهُ / رِجَالٌ',
      color: Colors.deepPurple,
      category: 'صفات الحروف',
    ),
  ];
}
