import 'package:flutter/material.dart';

class AsmaUlHusnaModel {
  final int id;
  final String name;
  final String meaning;
  final String description;

  const AsmaUlHusnaModel({
    required this.id,
    required this.name,
    required this.meaning,
    required this.description,
  });
}

class AsmaUlHusnaData {
  static const List<AsmaUlHusnaModel> names = [
    AsmaUlHusnaModel(id: 1, name: 'الرَّحْمَنُ', meaning: 'ذو الرحمة الشاملة', description: 'الذي وسعت رحمته جميع الخلائق في الدنيا، والمؤمنين والكافرين.'),
    AsmaUlHusnaModel(id: 2, name: 'الرَّحِيمُ', meaning: 'المفيض بالرحمة', description: 'الذي يرحم المؤمنين برحمة خاصة في الدنيا والآخرة.'),
    AsmaUlHusnaModel(id: 3, name: 'الْمَلِكُ', meaning: 'المالك المتصرف', description: 'الذي له الملك المطلق، المتصرف في خلقه بالأمر والنهي.'),
    AsmaUlHusnaModel(id: 4, name: 'الْقُدُّوسُ', meaning: 'الطاهر المنزه', description: 'المنزه عن كل نقص، والمطهر من كل عيب.'),
    AsmaUlHusnaModel(id: 5, name: 'السَّلَامُ', meaning: 'الخالي من الآفات', description: 'السالم من جميع العيوب والنقائص، والذي يسلم خلقه من ظلمه.'),
    AsmaUlHusnaModel(id: 6, name: 'الْمُؤْمِنُ', meaning: 'المصدق لرسله', description: 'الذي يصدق رسله بالمعجزات، ويؤمن عباده من الخوف والظلم.'),
    AsmaUlHusnaModel(id: 7, name: 'الْمُهَيْمِنُ', meaning: 'المراقب والحافظ', description: 'الرقيب الحافظ والمهيمن على كل شيء، يعلم خفايا الأمور.'),
    AsmaUlHusnaModel(id: 8, name: 'الْعَزِيزُ', meaning: 'القوي الغالب', description: 'الغالب الذي لا يقهره شيء، والقوي الذي لا يعجزه شيء.'),
    AsmaUlHusnaModel(id: 9, name: 'الْجَبَّارُ', meaning: 'المنفذ مشيئته', description: 'الذي يجبر قلوب المنكسرين، والذي يقهر الجبابرة ويغلبهم.'),
    AsmaUlHusnaModel(id: 10, name: 'الْمُتَكَبِّرُ', meaning: 'المتعالي عن صفات الخلق', description: 'المتعالي عن صفات الخلق، والذي تكبر عن كل سوء.'),
    AsmaUlHusnaModel(id: 11, name: 'الْخَالِقُ', meaning: 'المبدع للخلق', description: 'الذي أوجد جميع الأشياء من العدم وقدرها تقديراً.'),
    AsmaUlHusnaModel(id: 12, name: 'الْبَارِئُ', meaning: 'المميز لخلقه', description: 'الذي خلق الخلق بريئاً من التفاوت وعدم التناسب.'),
    AsmaUlHusnaModel(id: 13, name: 'الْمُصَوِّرُ', meaning: 'معطي الصور', description: 'الذي صور جميع الموجودات، ورتبها فأعطى كل شيء منها صورة خاصة.'),
    AsmaUlHusnaModel(id: 14, name: 'الْغَفَّارُ', meaning: 'الكثير المغفرة', description: 'الذي يغفر الذنوب ويستر العيوب مرة بعد مرة.'),
    AsmaUlHusnaModel(id: 15, name: 'الْقَهَّارُ', meaning: 'الغالب الخاضع له الخلائق', description: 'الذي قهر كل شيء، وخضع لجلاله كل موجود.'),
    AsmaUlHusnaModel(id: 16, name: 'الْوَهَّابُ', meaning: 'المعطي بلا عوض', description: 'الذي يجود بالعطاء المتكرر بغير سؤال وبغير عوض.'),
    AsmaUlHusnaModel(id: 17, name: 'الرَّزَّاقُ', meaning: 'خالق الأرزاق', description: 'الذي خلق الأرزاق والمتكفل بإيصالها لخلقه.'),
    AsmaUlHusnaModel(id: 18, name: 'الْفَتَّاحُ', meaning: 'فاتح أبواب الرحمة', description: 'الذي يفتح أبواب الرحمة والرزق لعباده، ويفتح قلوبهم وعيونهم ويبصرهم الحق.'),
    AsmaUlHusnaModel(id: 19, name: 'الْعَلِيمُ', meaning: 'المحيط علماً بكل شيء', description: 'الذي أحاط علمه بالظواهر والبواطن والإسرار والإعلانات.'),
    AsmaUlHusnaModel(id: 20, name: 'الْقَابِضُ', meaning: 'ممسك الأرزاق والنفوس', description: 'الذي يقبض الرزق عمن يشاء بحكمته.'),
    AsmaUlHusnaModel(id: 21, name: 'الْبَاسِطُ', meaning: 'موسع الأرزاق', description: 'الذي يبسط الرزق لمن يشاء بفضله ورحمته.'),
    AsmaUlHusnaModel(id: 22, name: 'الْخَافِضُ', meaning: 'المذل للمتكبرين', description: 'الذي يخفض الكفار والمتكبرين ويذلهم بقوة سلطانه.'),
    AsmaUlHusnaModel(id: 23, name: 'الرَّافِعُ', meaning: 'المعز للمؤمنين', description: 'الذي يرفع درجات المؤمنين الصالحين في الدنيا والآخرة.'),
    AsmaUlHusnaModel(id: 24, name: 'الْمُعِزُّ', meaning: 'الواهب للعزة', description: 'الذي يهب العزة لمن يشاء من عباده.'),
    AsmaUlHusnaModel(id: 25, name: 'الْمُذِلُّ', meaning: 'سالب العزة', description: 'الذي يسلب العزة عمن يشاء، ويذل الطغاة والمتكبرين.'),
    AsmaUlHusnaModel(id: 26, name: 'السَّمِيعُ', meaning: 'المدرك لكل الأصوات', description: 'الذي لا يخفى عليه صوت في الأرض ولا في السماء.'),
    AsmaUlHusnaModel(id: 27, name: 'الْبَصِيرُ', meaning: 'المدرك لكل المرئيات', description: 'الذي يبصر ويرى خفايا الأمور وما في الصدور.'),
    AsmaUlHusnaModel(id: 28, name: 'الْحَكَمُ', meaning: 'القاضي العدل', description: 'الذي يفصل بين عباده بالحق والعدل ولا متققب لحكمه.'),
    AsmaUlHusnaModel(id: 29, name: 'الْعَدْلُ', meaning: 'المنزه عن الظلم', description: 'الذي لا يظلم أحداً وكل أموره مستقيمة وحكمه عادل.'),
    AsmaUlHusnaModel(id: 30, name: 'اللَّطِيفُ', meaning: 'البر بعباده', description: 'الذي يعلم دقائق الأمور وغوامضها، ويرفق بعباده من حيث لا يعلمون.'),
    AsmaUlHusnaModel(id: 31, name: 'الْخَبِيرُ', meaning: 'العليم بدقائق الأمور', description: 'الذي يعلم المكنونات وما دق من الأمور وخفي منها.'),
    AsmaUlHusnaModel(id: 32, name: 'الْحَلِيمُ', meaning: 'الذي لا يعجل العقوبة', description: 'الذي لا يحبس نعمه عن عباده بسوء أفعالهم ولا يعجل بالعقوبة.'),
    AsmaUlHusnaModel(id: 33, name: 'الْعَظِيمُ', meaning: 'صاحب العظمة والجلال', description: 'الذي لا يصل العقل إلى كنه عظمته وجلاله.'),
    AsmaUlHusnaModel(id: 34, name: 'الْغَفُورُ', meaning: 'الساتر للذنوب والمجاوز عنها', description: 'الذي يكثر من ستر الذنوب والمغفرة مهما عظمت.'),
    AsmaUlHusnaModel(id: 35, name: 'الشَّكُورُ', meaning: 'المثيب على العمل القليل', description: 'الذي يزكو عنده العمل القليل، ويضاعف الأجر للمخلصين.'),
    AsmaUlHusnaModel(id: 36, name: 'الْعَلِيُّ', meaning: 'المتعالي عن الأنداد والأضداد', description: 'المرتفع قدراً ومكانة، ولا رتبة فوق رتبته ولا منزلة فوق منزلته.'),
    AsmaUlHusnaModel(id: 37, name: 'الْكَبِيرُ', meaning: 'العظيم الشأن', description: 'الذي كبر عن كل نقص وعيب، وهو أعظم وأكبر من كل شيء.'),
    AsmaUlHusnaModel(id: 38, name: 'الْحَفِيظُ', meaning: 'الصائن لكل شيء', description: 'الذي يحفظ السماوات والأرض ومن فيهن، ويحفظ أعمال العباد.'),
    AsmaUlHusnaModel(id: 39, name: 'الْمُقِيتُ', meaning: 'خالق الأقوات وموصلها', description: 'المتكفل بجميع الأقوات والمقدر لها.'),
    AsmaUlHusnaModel(id: 40, name: 'الْحَسِيبُ', meaning: 'الكافي الحافظ', description: 'الذي يكفي عباده همومهم ويحاسبهم على أعمالهم.'),
    AsmaUlHusnaModel(id: 41, name: 'الْجَلِيلُ', meaning: 'الكامل في صفاته', description: 'صاحب الجلال والكمال في ذاته وصفاته.'),
    AsmaUlHusnaModel(id: 42, name: 'الْكَرِيمُ', meaning: 'كثير الخير والعطاء', description: 'الذي يبتدئ بالعطية، ويتجاوز عن الذنب.'),
    AsmaUlHusnaModel(id: 43, name: 'الرَّقِيبُ', meaning: 'الملازم الذي لا يغفل', description: 'المطلع على كل شيء، الذي لا يغيب عنه شيء من أمور عباده.'),
    AsmaUlHusnaModel(id: 44, name: 'الْمُجِيبُ', meaning: 'مفيض العطاء للسائلين', description: 'الذي يجيب دعوة المضطرين والسائلين.'),
    AsmaUlHusnaModel(id: 45, name: 'الْوَاسِعُ', meaning: 'المحيط بكل شيء', description: 'الذي يسع كرسيه السماوات والأرض، ووسعت رحمته كل شيء.'),
    AsmaUlHusnaModel(id: 46, name: 'الْحَكِيمُ', meaning: 'المنزه عن فعل الخلل', description: 'الذي يضع الأشياء في مواضعها بحكمة وتدبير.'),
    AsmaUlHusnaModel(id: 47, name: 'الْوَدُودُ', meaning: 'المحب لأوليائه والمحبوب لهم', description: 'الذي يحب عباده الصالحين ويحبونه.'),
    AsmaUlHusnaModel(id: 48, name: 'الْمَجِيدُ', meaning: 'البالغ النهاية في المجد', description: 'العظيم الجليل العالي التام في المجد والكبرياء.'),
    AsmaUlHusnaModel(id: 49, name: 'الْبَاعِثُ', meaning: 'محيي الموتى', description: 'الذي يبعث الموتى يوم القيامة للجزاء والحساب.'),
    AsmaUlHusnaModel(id: 50, name: 'الشَّهِيدُ', meaning: 'العالم بالأمور المطلع عليها', description: 'الذي لا يغيب عنه شيء ولا يعزب عنه مثقال ذرة.'),
    AsmaUlHusnaModel(id: 51, name: 'الْحَقُّ', meaning: 'المتصف بالوجود الثابت', description: 'الذي لا شك في وجوده ولا ريب في ألوهيته.'),
    AsmaUlHusnaModel(id: 52, name: 'الْوَكِيلُ', meaning: 'المنتظر والمفوض إليه الأمور', description: 'الذي وكلت إليه الأمور وتكفل بأرزاق العباد ومصالحهم.'),
    AsmaUlHusnaModel(id: 53, name: 'الْقَوِيُّ', meaning: 'صاحب القدرة التامة', description: 'الذي لا يعجزه شيء ولا يقهره شيء.'),
    AsmaUlHusnaModel(id: 54, name: 'الْمَتِينُ', meaning: 'الشديد القوة', description: 'الذي لا تلحقه مشقة في أفعاله ولا يتطرق إليه التعب.'),
    AsmaUlHusnaModel(id: 55, name: 'الْوَلِيُّ', meaning: 'الناصر والمعين', description: 'المحب لـ ونصير المؤمنين والمتبني لنصرتهم.'),
    AsmaUlHusnaModel(id: 56, name: 'الْحَمِيدُ', meaning: 'المستحق للحمد', description: 'المحمود في ذاته وصفاته وأفعاله.'),
    AsmaUlHusnaModel(id: 57, name: 'الْمُحْصِي', meaning: 'العالم بكميات الأشياء', description: 'الذي لا يفوته دقيق ولا جليل إلا أحصاه وكتبه.'),
    AsmaUlHusnaModel(id: 58, name: 'الْمُبْدِئُ', meaning: 'خالق الأشياء ابتداء', description: 'الذي بدأ الخلق وأوجده من العدم.'),
    AsmaUlHusnaModel(id: 59, name: 'الْمُعِيدُ', meaning: 'مرجع الخلائق بعد الموت', description: 'الذي يعيد الخلق بعد الموت للحساب والجزاء.'),
    AsmaUlHusnaModel(id: 60, name: 'الْمُحْيِي', meaning: 'واهب الحياة', description: 'الذي يحيي الأجساد الرميم وينفخ فيها الروح.'),
    AsmaUlHusnaModel(id: 61, name: 'الْمُمِيتُ', meaning: 'سالب الحياة', description: 'الذي قدر الموت على الخلائق وقهرهم به.'),
    AsmaUlHusnaModel(id: 62, name: 'الْحَيُّ', meaning: 'المتصف بالحياة الدائمة', description: 'الذي لا يموت وباقٍ في كل حين وأوان.'),
    AsmaUlHusnaModel(id: 63, name: 'الْقَيُّومُ', meaning: 'القائم بنفسه والمقيم لغيره', description: 'لا يحتاج إلى أحد، والكل محتاجون إليه في حفظهم ووجودهم.'),
    AsmaUlHusnaModel(id: 64, name: 'الْوَاجِدُ', meaning: 'المدرك لكل شيء', description: 'لا يغيب عنه شيء ولا يعوزه شيء.'),
    AsmaUlHusnaModel(id: 65, name: 'الْمَاجِدُ', meaning: 'المتصف بالكبرياء والشرف', description: 'تأكيد لمعنى المجيد وفيه مزيد من النبل والكرم.'),
    AsmaUlHusnaModel(id: 66, name: 'الْوَاحِدُ', meaning: 'المنفرد عن التجزئة', description: 'الذي لا شبيه له ولا ثاني له ولا شريك له.'),
    AsmaUlHusnaModel(id: 67, name: 'الْأَحَدُ', meaning: 'المتفرد الفرد', description: 'فرد لا نظير له ولا وزير، ولا شبيه ولا نديد.'),
    AsmaUlHusnaModel(id: 68, name: 'الصَّمَدُ', meaning: 'المقصود في الحوائج', description: 'السيد الذي يُقصد إليه في الحوائج والملمّات.'),
    AsmaUlHusnaModel(id: 69, name: 'الْقَادِرُ', meaning: 'صاحب القدرة المنفذ لها', description: 'القادر على كل شيء يفعل ما يشاء ويحكم ما يريد.'),
    AsmaUlHusnaModel(id: 70, name: 'الْمُقْتَدِرُ', meaning: 'البالغ في القدرة تمامها', description: 'المسيطر والمتحكم بقدرة لا يعجزها شيء المطلقة.'),
    AsmaUlHusnaModel(id: 71, name: 'الْمُقَدِّمُ', meaning: 'المعطي المراتب والمنازل', description: 'الذي يقدم عباده الصالحين ويدنيهم ويرفع منازلهم.'),
    AsmaUlHusnaModel(id: 72, name: 'الْمُؤَخِّرُ', meaning: 'المؤخر لمن يشاء', description: 'الذي يؤخر الطغاة والمشركين وينزل مراتبهم.'),
    AsmaUlHusnaModel(id: 73, name: 'الْأَوَّلُ', meaning: 'السابق لكل شيء', description: 'الذي ليس قبله شيء وهو بداية كل شيء.'),
    AsmaUlHusnaModel(id: 74, name: 'الْآخِرُ', meaning: 'الباقي بعد فناء كل شيء', description: 'الذي ليس بعده شيء ويبقى بعد فناء الخلائق.'),
    AsmaUlHusnaModel(id: 75, name: 'الظَّاهِرُ', meaning: 'الغالب البين', description: 'الذي ليس فوقه شيء، المتجلي بآياته وتدبيره والخفي بذاته.'),
    AsmaUlHusnaModel(id: 76, name: 'الْبَاطِنُ', meaning: 'العالم بالخفايا', description: 'الذي ليس دونه شيء والمدرك لكل الأمور الباطنة.'),
    AsmaUlHusnaModel(id: 77, name: 'الْوَالِي', meaning: 'المالك المتصرف بالأمور', description: 'الذي يتولى أمور الخلائق بلطفه وعنايته وحفظه ويدبرها.'),
    AsmaUlHusnaModel(id: 78, name: 'الْمُتَعَالِي', meaning: 'المرتفع المنيع', description: 'الجل المرتفع عن صفات المخلوقين وما يلحقهم من صفات النقص.'),
    AsmaUlHusnaModel(id: 79, name: 'الْبَرُّ', meaning: 'الواسع الإحسان واللطف', description: 'المحسن إلى عباده في الدين والدنيا وأمورهم.'),
    AsmaUlHusnaModel(id: 80, name: 'التَّوَّابُ', meaning: 'القابل لتوبة عباده', description: 'الذي يعود على من تاب إليه برأفته ورحمته ومغفرته.'),
    AsmaUlHusnaModel(id: 81, name: 'الْمُنْتَقِمُ', meaning: 'المعاقب للطغاة', description: 'الذي يقصم ظهور العصاة والطغاة والمتمردين.'),
    AsmaUlHusnaModel(id: 82, name: 'الْعَفُوُّ', meaning: 'الماحي للسيئات', description: 'الذي يمحو الذنوب ويتجاوز عن الزلات ويترك العقاب عليها.'),
    AsmaUlHusnaModel(id: 83, name: 'الرَّءُوفُ', meaning: 'العطوف الرحيـم', description: 'شديد الرحمة الذي يدرأ السوء عن عباده بلطفه وعنايته.'),
    AsmaUlHusnaModel(id: 84, name: 'مَالِكُ الْمُلْكِ', meaning: 'المنفرد بالتصرف في كل شيء', description: 'يؤتي الملك من يشاء وينزع الملك ممن يشاء.'),
    AsmaUlHusnaModel(id: 85, name: 'ذُو الْجَلَالِ وَالْإِكْرَامِ', meaning: 'المتصف بالعظمة والإنعام', description: 'أهل الجلال والكمال والكبرياء، والمستحق للتعظيم والتكريم.'),
    AsmaUlHusnaModel(id: 86, name: 'الْمُقْسِطُ', meaning: 'العادل في حكمه', description: 'الذي ينصف المظلوم من الظالم ويرضي الخصوم بعدله وكرمه.'),
    AsmaUlHusnaModel(id: 87, name: 'الْجَامِعُ', meaning: 'الجامع للخلائق للحساب', description: 'الذي يجمع الخلائق ليوم لا ريب فيه ليجزيهم بأعمالهم.'),
    AsmaUlHusnaModel(id: 88, name: 'الْغَنِيُّ', meaning: 'المستغني عن الخلائق', description: 'لا يحتاج لأحد وكل شيء يحتاج إليه في كل الأمور والأحوال.'),
    AsmaUlHusnaModel(id: 89, name: 'الْمُغْنِي', meaning: 'معطي الغنى', description: 'الذي يكفي عباده ويغنيهم عن من سواه بما أعطاهم من نعم.'),
    AsmaUlHusnaModel(id: 90, name: 'الْمَانِعُ', meaning: 'مانع البلاء والأذى', description: 'يحمي من يشاء ويمنع عنهم الضر والبلاء ويعطي لمن يشاء ويمنع عمن يشاء.'),
    AsmaUlHusnaModel(id: 91, name: 'الضَّارُّ', meaning: 'الذي يلحق الضرر لمن يشاء', description: 'يقدر الضرر لمن شاء من عباده بحكمة وعدل.'),
    AsmaUlHusnaModel(id: 92, name: 'النَّافِعُ', meaning: 'مقدر المنفعة والخير', description: 'الذي يوصل النفع والخير لعباده كيف شاء وكما يريد.'),
    AsmaUlHusnaModel(id: 93, name: 'النُّورُ', meaning: 'الظاهر البين', description: 'نور السماوات والأرض، الذي بنوره يهتدي الضال ويرشد.'),
    AsmaUlHusnaModel(id: 94, name: 'الْهَادِي', meaning: 'المرشد لطريق الحق', description: 'الذي يهدي القلوب للإيمان ويوجه عباده لمصالحهم.'),
    AsmaUlHusnaModel(id: 95, name: 'الْبَدِيعُ', meaning: 'المخترع للخلق', description: 'الذي خلق الأشياء على غير مثال سابق، المبدع في الكون.'),
    AsmaUlHusnaModel(id: 96, name: 'الْبَاقِي', meaning: 'الذي لا يَفْنَى', description: 'الموجود الدائم الذي لا يتطرق إليه الفناء وهو الحي الذي لا يموت.'),
    AsmaUlHusnaModel(id: 97, name: 'الْوَارِثُ', meaning: 'الباقي بعد فناء كل الخلائق', description: 'ترجع إليه الأملاك بعد فناء أصحابها وإليه ترجع الأمور.'),
    AsmaUlHusnaModel(id: 98, name: 'الرَّشِيدُ', meaning: 'المرشد لكل خير', description: 'الذي أرشد الخلق لسننه، وصرفهم لمصالحه وتدبيره بحكمه.'),
    AsmaUlHusnaModel(id: 99, name: 'الصَّبُورُ', meaning: 'الذي يمهل المذنبين', description: 'الذي لا يعجل بالعقوبة بل يمهل العاصين لعلهـم من ذنوبهم يتوبون.'),
  ];
}
